import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Home } from '../components/Home'
import {signIn, signOut, useSession} from "next-auth/client"
import { useEffect, useState } from 'react';

import { faConciergeBell } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;

export default function App() {
  const [session, loading] = useSession();
  const [initLogin, setInitLogin] = useState(false)

  useEffect(async() => {   
    if(session && initLogin){
      const res = await fetch("http://localhost:3000/api/user")
      const { data } = await res.json();
      for(let i = 0; i < data; i++){
        if(data[i].username !== session.user.username){
          await fetch("http://localhost:3000/api/user", {
            method: "POST",
            headers: {
              "Accept": "application/json",
              "Content-Type": "application/json"
            },
            body: JSON.stringify({ username: session.user.name || session.user.email })
          })
          setInitLogin(false)
        }
      }
      
    }
  }, [session])

  return (
    <div className={styles.container}>
      <Head>
        <title>Personal Concierge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!session && 
      <div className={styles.signInContainer}>
        <span>WELCOME, CLICK THE BELL TO CALL THE CONCIERGE</span>
        <div className={styles.signInBtn} onClick={signIn}>
          <FontAwesomeIcon className={styles.conciergeBell} icon={faConciergeBell} size="3x" />
        </div>
      </div>
      }

      {session && 
      <Home />
      }
      
    </div>
  )
}

